// <auto-generated />
using System;
using Gruuber.Rides.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gruuber.Rides.Infrastructure.Migrations
{
    [DbContext(typeof(RidesDbContext))]
    [Migration("20260523123505_AddSurgePricingAndRideFare")]
    partial class AddSurgePricingAndRideFare
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gruuber.Rides.Domain.Ride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("BaseFare")
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("DestLat")
                        .HasColumnType("double precision");

                    b.Property<double?>("DestLng")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("FinalFare")
                        .HasColumnType("numeric(10,2)");

                    b.Property<double>("PickupLat")
                        .HasColumnType("double precision");

                    b.Property<double>("PickupLng")
                        .HasColumnType("double precision");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer");

                    b.Property<string>("RideType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("RiderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SurgeMultiplier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(6,2)")
                        .HasDefaultValue(1.0m);

                    b.Property<string>("SurgeReason")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Status", "RegionId");

                    b.ToTable("rides", (string)null);
                });

            modelBuilder.Entity("Gruuber.Rides.Domain.SurgePricingConfig", b =>
                {
                    b.Property<int>("RegionId")
                        .HasColumnType("integer");

                    b.Property<string>("RideType")
                        .HasColumnType("text");

                    b.Property<decimal>("DemandRatioThreshold")
                        .HasColumnType("numeric(4,3)");

                    b.Property<decimal>("MaxMultiplier")
                        .HasColumnType("numeric(6,2)");

                    b.Property<decimal>("Multiplier")
                        .HasColumnType("numeric(6,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RegionId", "RideType", "DemandRatioThreshold");

                    b.ToTable("surge_config", (string)null);
                });

            modelBuilder.Entity("Gruuber.Rides.Domain.SurgeTimeRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Multiplier")
                        .HasColumnType("numeric(6,2)");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer");

                    b.Property<string>("RideType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("surge_time_rules", (string)null);
                });

            modelBuilder.Entity("Gruuber.Rides.Infrastructure.RideOutboxEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ride_outbox", (string)null);
                });

            modelBuilder.Entity("Gruuber.Rides.Infrastructure.RideView", b =>
                {
                    b.Property<Guid>("RideId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double>("Lng")
                        .HasColumnType("double precision");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RideId");

                    b.HasIndex("DriverId", "Status");

                    b.ToTable("ride_views", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
