// <auto-generated />
using System;
using Gruuber.Analytics.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gruuber.Analytics.Migrations
{
    [DbContext(typeof(AnalyticsDbContext))]
    [Migration("20260523133529_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gruuber.Analytics.Domain.AdminStatsDaily", b =>
                {
                    b.Property<int>("RegionId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StatDate")
                        .HasColumnType("date");

                    b.Property<int>("ActiveDrivers")
                        .HasColumnType("integer");

                    b.Property<int>("ActiveRestaurants")
                        .HasColumnType("integer");

                    b.Property<decimal>("GrossPlatformRevenue")
                        .HasColumnType("numeric(14,2)");

                    b.Property<int>("TotalOrders")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPoolRides")
                        .HasColumnType("integer");

                    b.Property<int>("TotalRides")
                        .HasColumnType("integer");

                    b.HasKey("RegionId", "StatDate");

                    b.ToTable("admin_stats_daily", (string)null);
                });

            modelBuilder.Entity("Gruuber.Analytics.Domain.AnalyticsExportJob", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DownloadUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("FromDate")
                        .HasColumnType("date");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("ToDate")
                        .HasColumnType("date");

                    b.HasKey("JobId");

                    b.HasIndex("OwnerId", "Status");

                    b.ToTable("analytics_export_jobs", (string)null);
                });

            modelBuilder.Entity("Gruuber.Analytics.Domain.DriverStatsDaily", b =>
                {
                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StatDate")
                        .HasColumnType("date");

                    b.Property<decimal>("AcceptanceRate")
                        .HasColumnType("numeric(4,3)");

                    b.Property<decimal>("AvgRating")
                        .HasColumnType("numeric(3,2)");

                    b.Property<decimal>("BonusEarnings")
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("GrossEarnings")
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("OnlineMinutes")
                        .HasColumnType("integer");

                    b.Property<decimal>("PayoutAmount")
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("PoolTrips")
                        .HasColumnType("integer");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer");

                    b.Property<int>("TripsCancelled")
                        .HasColumnType("integer");

                    b.Property<int>("TripsCompleted")
                        .HasColumnType("integer");

                    b.HasKey("DriverId", "StatDate");

                    b.ToTable("driver_stats_daily", (string)null);
                });

            modelBuilder.Entity("Gruuber.Analytics.Domain.MenuItemStatsDaily", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<string>("ItemName")
                        .HasColumnType("text");

                    b.Property<DateOnly>("StatDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("UnitsSold")
                        .HasColumnType("integer");

                    b.HasKey("RestaurantId", "ItemName", "StatDate");

                    b.ToTable("menu_item_stats_daily", (string)null);
                });

            modelBuilder.Entity("Gruuber.Analytics.Domain.ProcessedAnalyticsEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EventId");

                    b.ToTable("processed_analytics_events", (string)null);
                });

            modelBuilder.Entity("Gruuber.Analytics.Domain.RestaurantStatsDaily", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StatDate")
                        .HasColumnType("date");

                    b.Property<int>("AvgPrepTimeSecs")
                        .HasColumnType("integer");

                    b.Property<decimal>("AvgRating")
                        .HasColumnType("numeric(3,2)");

                    b.Property<decimal>("GrossRevenue")
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("OrdersCancelled")
                        .HasColumnType("integer");

                    b.Property<int>("OrdersCompleted")
                        .HasColumnType("integer");

                    b.Property<int>("OrdersReceived")
                        .HasColumnType("integer");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer");

                    b.HasKey("RestaurantId", "StatDate");

                    b.ToTable("restaurant_stats_daily", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
